<a href="https://colab.research.google.com/github/minmings111/practice-numpy/blob/main/multi_dimensional_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [10]:
# 1차원 배열
A = np.array([1, 2, 3, 4])
print(A)
print(np.ndim(A))
print(A.shape)
print(A.shape[0])

[1 2 3 4]
1
(4,)
4


In [12]:
# 2차원 배열 == 행렬 == matrix
B = np.array([[1, 2], [3, 4,], [5, 6]])
print(B)
print(np.ndim(B))
print(B.shape)
print(B.shape[0]) # shape이 알려주는 배열 구조에서 가장 바깥쪽 기준인 'Row의 개수'를 반환

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)
3


In [16]:
A = np.array([[1, 2], [3, 4]])
print(A.shape)

B = np.array([[5, 6], [7, 8]])
print(B.shape)

np.dot(A,B)

(2, 2)
(2, 2)


array([[19, 22],
       [43, 50]])

In [19]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A.shape)

B = np.array([[1, 2], [3, 4], [5, 6]])
print(B.shape)

# 행렬의 형상에 주의할 것!
# 행렬 A의 1번째 차원의 원소 수(열 수)와
# 행렬 B의 0번째 차원의 원소 수(행 수)가 같아야 행렬의 곱을 계산할 수 있음
np.dot(A, B)

(2, 3)
(3, 2)


array([[22, 28],
       [49, 64]])

In [23]:
C = np.array([[1, 2], [3, 4]])
print(C.shape)
print(A.shape)

# 행렬 A의 1번째 차원과 행렬 C의 0번째 차원 원소 수가 다름
np.dot(A, C)

(2, 2)
(2, 3)


ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [39]:
# 행렬의 곱은 교환법칙이 성립하지 않음
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(A.shape)
print(B.shape)

C = np.dot(A, B)
print(C.shape)

(3, 2)
(2, 4)
(3, 4)


In [33]:
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([7, 8])

print(A.shape)
print(B.shape)

C = np.dot(A, B)
print(C)
print(C.shape)

(3, 2)
(2,)
[23 53 83]
(3,)


In [38]:
X = np.array([1, 2])
print(X.shape)

W = np.array([[1, 3, 5], [2, 4, 6]])
print(W.shape)
print(W)

Y = np.dot(X, W)
print(Y)

(2,)
(2, 3)
[[1 3 5]
 [2 4 6]]
[ 5 11 17]


In [42]:
X = np.array([1.0, 0.5])
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
B1 = np.array([0.1, 0.2, 0.3])

print(X.shape)
print(W1.shape)

# 1차원 배열은 가로, 세로라는 방향의 개념 없이 1차원 구조라 (3,) 구조로 출력됨.
print(B1.shape)

A1 = np.dot(X, W1) + B1
A1

(2,)
(2, 3)
(3,)


array([0.3, 0.7, 1.1])

In [45]:
# 활성화 함수: 시그모이드
# 입력층(0층) -> 은닉층(1층)
def sigmoid(x):
  return 1 / (1 + np.exp(-x))


Z1 = sigmoid(A1) # 1층의 최종 결과값

print(A1)
print(Z1)

[0.3 0.7 1.1]
[0.57444252 0.66818777 0.75026011]


In [50]:
# 1층 -> 2층
W2 = np.array([[0.1, 0.4], [0.2, 0.5] , [0.3, 0.6]])
B2 = np.array([0.1, 0.2])

print(W2.shape)
print(B2.shape)

print(Z1.shape)

A2 = np.dot(Z1, W2) + B2 # 1층의 최종 결과값이 인자가 됨
Z2 = sigmoid(A2) # 2층의 최종 결과값

print(A2)
print(Z2)

(3, 2)
(2,)
(3,)
[0.51615984 1.21402696]
[0.62624937 0.7710107 ]


In [58]:
# 출력층

# 출력층의 활성화 함수는 풀고자 하는 문제의 성질에 맞추어 선택함.
# 활성화 함수: 항등 함수(입력을 그대로 출력하는 함수)
def identity_function(x):
  return x

W3 = np.array([[0.1, 0.3], [0.2, 0.4]])
B3 = np.array([0.1, 0.2])

A3 = np.dot(Z2, W3) + B3

Y = identity_function(A3)

print(Y)

[0.31682708 0.69627909]


In [59]:
# 구현 정리
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

def identity_function(x):
  return x

def init_network():
  network = {} # 빈 딕셔너리 선언

  network["W1"] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
  network["b1"] = np.array([0.1, 0.2, 0.3])
  network["W2"] = np.array([[0.1, 0.4], [0.2, 0.5] , [0.3, 0.6]])
  network["b2"] = np.array([0.1, 0.2])
  network["W3"] = np.array([[0.1, 0.3], [0.2, 0.4]])
  network["b3"] = np.array([0.1, 0.2])

  return network

def forward(network, x):
  W1, W2, W3 = network["W1"], network["W2"], network["W3"]
  b1, b2, b3 = network["b1"], network["b2"], network["b3"]

  a1 = np.dot(x, W1) + b1
  z1 = sigmoid(a1)
  a2 = np.dot(z1, W2) + b2
  z2 = sigmoid(a2)
  a3 = np.dot(z2, W3) + b3
  y = identity_function(a3)

  return y

network = init_network() # 네트워크 변수 초기화
x = np.array([1.0, 0.5]) # 최초 x 인자 전달
y = forward(network, x) # 순방향 계산
print(y)

[0.31682708 0.69627909]
