<a href="https://colab.research.google.com/github/minmings111/practice-numpy/blob/main/practice_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
x = np.array([1.0, 2.0, 3.0])
print(x)
type(x)

[1. 2. 3.]


numpy.ndarray

In [6]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])

In [8]:
x+y

array([3., 6., 9.])

In [53]:
x = np.array([1.0, 2.0, 3.0])

# 여기서 2.0은 스칼라(크기만 있고, 방향X)
x / 2.0 # 브로드캐스트!

array([0.5, 1. , 1.5])

In [21]:
A = np.array([[1, 2], [3, 4]])
print(A)
print("A행렬의 형상 :", A.shape)
print("A행렬의 자료형 :", A.dtype)

[[1 2]
 [3 4]]
A행렬의 형상 : (2, 2)
A행렬의 자료형 : int64


In [23]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[3, 0], [0, 6]])
A*B

array([[ 3,  0],
       [ 0, 24]])

In [27]:
A = np.array([[1, 2], [3, 4]]) #2차원 배열
B = np.array([10, 20]) # 1차원 배열

print("A행렬의 형상 :", A.shape)
print("A행렬의 자료형 :", A.dtype)
print("B행렬의 형상 :", B.shape)
print("B행렬의 자료형 :", B.dtype)

A*B # 브로드캐스트!

A행렬의 형상 : (2, 2)
A행렬의 자료형 : int64
B행렬의 형상 : (2,)
B행렬의 자료형 : int64


array([[10, 40],
       [30, 80]])

In [30]:
A = np.array([[[1, 1], [1, 1], [1, 1]]]) #2차원 배열
B = np.array([[2, 2], [3, 3]]) # 1차원 배열

print("A행렬의 형상 :", A.shape)
print("A행렬의 자료형 :", A.dtype)
print("B행렬의 형상 :", B.shape)
print("B행렬의 자료형 :", B.dtype)

A*B # 브로드캐스트 불가!
# 두 배열의 차원을 뒤에서부터(오른쪽에서 왼쪽으로) 비교했을 때
# 각 축(Axis)의 크기가 같거나, 둘 중 하나가 1이어야 함

A행렬의 형상 : (1, 3, 2)
A행렬의 자료형 : int64
B행렬의 형상 : (2, 2)
B행렬의 자료형 : int64


ValueError: operands could not be broadcast together with shapes (1,3,2) (2,2) 

In [34]:
X = np.array([[51, 55], [14, 19], [0, 4]])

print(X)

# 행렬도 인덱스로 접근 가능
X[0]
X[0][1]

[[51 55]
 [14 19]
 [ 0  4]]


np.int64(55)

In [44]:
# for 문으로도 접근 가능
for row in X:
  print(row)

51
55
14
19
0
4


In [43]:
# X를 1차원 배열로 변환(평탄화)
# 평탄화하는 이유: 다차원 구조와 상관없이 원하는 조건이나 특정 위치에 있는 데이터만
# 한 줄로 보기 좋게 추려내기 위함
X = np.array([[51, 55], [14, 19], [0, 4]])
X = X.flatten()
print(X)

#X의 인덱스가 0, 2, 4인 원소 얻기
X[np.array([0, 2, 4])]

[51 55 14 19  0  4]


array([51, 14,  0])

In [51]:
# 조건 확인
# 배열의 모든 원소를 하나씩 15와 비교하여,
# 조건에 맞으면 True, 틀리면 False를 넣은 불리언(Boolean) 배열 반환
X > 15

array([ True,  True, False,  True, False, False])

In [52]:
# 값 추출
# True/False 배열에서 True가 위치한 자리에 있는 실제 원소들만 추출해서 새로운 배열 생성
X[X>15]

array([51, 55, 19])