<a href="https://colab.research.google.com/github/minmings111/practice-numpy/blob/main/softmax_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [5]:
a = np.array([0.3, 2.9, 4.0])

exp_a = np.exp(a) # 지수 함수
print(exp_a)

sum_exp_a = np.sum(exp_a) # 지수 함수의 합
print(sum_exp_a)

y = exp_a / sum_exp_a
print(y)

[ 1.34985881 18.17414537 54.59815003]
74.1221542101633
[0.01821127 0.24519181 0.73659691]


In [9]:
# softmax function

def softmax(a):
  exp_a = np.exp(a)
  sum_exp_a = np.sum(exp_a)

  y = exp_a / sum_exp_a

  return y


In [14]:
# 소프트맥스 함수는 컴퓨터로 계산 시, overflow 문제가 있음
# 값이 너무 쉽게 큰 값을 내뱉음... e^1000은 무한대처럼 큰 값이 되어버림..

a = np.array([1010, 1000, 990])

np.exp(a) / np.sum(np.exp(a)) # 소프트맥스 함수의 계산
# array([nan, nan, nan]) 출력됨

/tmp/ipykernel_1076/3840126228.py:6: RuntimeWarning: overflow encountered in exp
  np.exp(a) / np.sum(np.exp(a)) # 소프트맥스 함수의 계산
/tmp/ipykernel_1076/3840126228.py:6: RuntimeWarning: invalid value encountered in divide
  np.exp(a) / np.sum(np.exp(a)) # 소프트맥스 함수의 계산


array([nan, nan, nan])

In [15]:
# 오버플로우 문제 개선 버전
def softmax(a):
  c = np.max(a) # 최댓값
  exp_a = np.exp(a-c) # 분자에서 최댓값 빼줌

  # 이미 뺀 값을 더하므로 분모에도 -최대값이 반영되어 있음.
  # 분자와 분모에 같은 값을 계산했으므로, 스케일만 작아지고 같은 계산임.
  sum_exp_a = np.sum(exp_a)
  y = exp_a / sum_exp_a

  return y

In [20]:
# softmax 함수의 특징

# softmax 함수의 출력은 0에서 1.0 사이의 실수이고, 출력의 총합은 1
# 이 성질을 이용하여 softmax 함수의 출력을 "확률"로 해석 가능
# 주의 : 각 원소의 대소관계는 변하지 않음

a = np.array([0.3, 2.9, 4.0])
y = softmax(a)

# y[0]의 확률, y[1]의 확률, y[2]의 확률
print(y)

np.sum(y)

[0.01821127 0.24519181 0.73659691]


np.float64(1.0)